build:
  services:
    - docker:dind
  image: docker:stable
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - echo "Alumix bot image available at  $CI_REGISTRY_IMAGE"
  only:
    - main
    - dev
    - refactory # to remove in future, after the refactory merge
